#!/usr/bin/env php
<?php

if(isset($argv[1])) {
    $arr = json_decode($argv[1],true);
    if(!is_array($arr) && empty($arr) ) {
        var_dump($arr);
    } else {
        echo json_encode($arr,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),PHP_EOL;
    }
} else {
    echo 'Usage: jsondecode \'{"name":"zhang san","desc":"IT engineer"}\'';
}

