#!/usr/bin/env php
<?php
date_default_timezone_set("PRC");
$arrDateTime = array();
//var_dump($argv);

if(isset($argv[1])) {
    if(!preg_match('/^\d{4}\-\d{1,2}\-\d{1,2}$/', $argv[1])) {
        echo "date formate error";
        die();
    }
    $arrDateTime[] = $argv[1];
}


if(isset($argv[2])) {
    if(empty($argv[1])) {
        echo "date formate error";
        die();
    }

    if(!preg_match('/^\d{1,2}\:\d{1,2}\:\d{1,2}$/', $argv[2])) {
        echo "time formate error";
        die();
    }
    $arrDateTime[] = $argv[2];
}




if(!empty($arrDateTime)) {
    $strTime = implode(' ', $arrDateTime);
    echo strtotime($strTime),PHP_EOL;
} else {
    $intTime = time();
    echo date('Y-m-d H:i:s'),"\t",time(), PHP_EOL;
}

