#!/usr/bin/env php
<?php
$strdate=date("Ymd");
if ( !isset($argv[1])|| strlen($argv[1]) == 0) {
	echo "ERR: 请输入文件名",PHP_EOL;
	die();
}
$filename = $strdate;
if ($argv[1] != '-') {
    $filename .= $argv[1];
}
exec("touch ${filename}");
