#!/bin/bash

set -e # 告诉bash如果任何语句的执行结果不是true则应该退出。


start() {
	echo "start webserver "
	restart
}

stop() {

	phpfpmctl stop && nginxctl stop
}


restart() {
	phpfpmctl restart && nginxctl restart
}

case  "$1" in 
	start)
		stop
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		echo "this is default"

esac